---
- name: Configure ACLs on Arista Switches
  hosts: LEAF1
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Create ACLs
      eos_acls:
        config:
        - afi: ipv4   #Specify ipv4 or ipv6 for the address family that you are creating
          acls:
          - name: TestACL   #Give your ACL a fun and useful name here
            aces:
            - sequence: 10    #Give you ACE entry a sequence number
              grant: permit   #Permit or deny traffic
              protocol: icmp  #Specify the protocol for the ACE
              source:         #Specify the source address
                any: true
              destination:    #Specify the destination address
                any: true
        state: merged         #Specify the state of the ACL
